"""
Bridge Agent - USP Agent with Backend Service Integration

A USP agent implementation that:
- Handles Device.LocalAgent.* data model locally (agent metadata, subscriptions, etc.)
- Forwards all other requests to backend services via uspbridge architecture
- Owns Boot! and Periodic! event generation (agent responsibilities)
- Uses two-channel pattern for decoupled TX/RX

This eliminates the need for full data model implementation in the agent itself,
allowing the agent to focus on protocol handling while delegating service-specific
logic to backend components.
"""

import asyncio
import logging
import time
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field

from message.request import (
    GetRequest, SetRequest, OperateRequest,
    GetSupportedDMRequest, GetInstancesRequest
)
from message.response import (
    GetResponse, SetResponse, OperateResponse,
    GetSupportedDMResponse, GetInstancesResponse
)
from uspbridge.base import UspBridge
from uspbridge.wrp_bridge import BridgeContext
from agent.agent_db import Database


logger = logging.getLogger(__name__)


@dataclass
class PendingRequest:
    """Track pending backend requests for response correlation"""
    request: Any
    context: BridgeContext
    timestamp: float = field(default_factory=time.time)
    future: Optional[asyncio.Future] = None


class BridgeAgent:
    """
    USP Agent that bridges requests to backend services
    
    Architecture:
    - Local: Device.LocalAgent.* (agent metadata, boot params, subscriptions)
    - Bridged: Everything else (Device.WiFi.*, Device.IP.*, Device.Ethernet.*, etc.)
    - Events: Boot! and Periodic! generated by agent, others forwarded from backend
    
    Example:
        # Create bridge (WRP, RBUS, etc.)
        bridge = WrpBridge(
            mac_address="112233445566",
            transport_send=lambda data: transport.send(data)
        )
        
        # Create agent
        agent = BridgeAgent(
            endpoint_id="proto::agent-1",
            bridge=bridge,
            local_dm_file="agent/local-dm.json",
            local_db_file="agent/local-db.json"
        )
        
        # Start event loop
        await agent.start()
        
        # Handle incoming request
        response = await agent.handle_get(get_request, controller_context)
    """
    
    # Local data model paths (handled by agent via local bridge)
    LOCAL_PATHS = [
        "Device.LocalAgent.",
        "Device.DeviceInfo.BootFirmwareVersion",  # Boot info
        "Device.DeviceInfo.UpTime",              # Agent uptime
        "Device.DeviceInfo.SoftwareVersion"      # Agent version
    ]
    
    def __init__(self, endpoint_id: str, bridge: UspBridge):
        """
        Initialize bridge agent
        
        Args:
            endpoint_id: Agent endpoint ID (e.g., "proto::agent-1")
            bridge: UspBridge for WRP/backend communication
                   Uses endpoint ID to distinguish internal vs external requests:
                   - Internal (local DB): Uses agent's own endpoint_id
                   - External (controller): Uses controller's endpoint from context
        """
        self.endpoint_id = endpoint_id
        self.bridge = bridge
        
        # Pending backend requests (for response correlation)
        self._pending: Dict[str, PendingRequest] = {}
        
        # Event generation state
        self._boot_time = time.time()
        self._periodic_interval = 300  # 5 minutes default
        self._periodic_task = None
        
        # Backend response listener task
        self._rx_task = None
        
    async def start(self):
        """Start agent event loops"""
        # Start periodic event generation
        self._periodic_task = asyncio.create_task(self._periodic_event_loop())
        
        # Start backend response listener (RX channel)
        self._rx_task = asyncio.create_task(self._backend_response_loop())
        
        # Send Boot! event
        await self._send_boot_event()
        
        logger.info(f"BridgeAgent started: {self.endpoint_id}")
    
    async def stop(self):
        """Stop agent event loops"""
        if self._periodic_task:
            self._periodic_task.cancel()
        if self._rx_task:
            self._rx_task.cancel()
        
        logger.info(f"BridgeAgent stopped: {self.endpoint_id}")
    
    # =========================================================================
    # Request Handlers (Main USP Operations)
    # =========================================================================
    
    async def handle_get(self, request: GetRequest, 
                        controller_context: Any) -> GetResponse:
        """
        Handle USP Get request
        
        Routes paths to local DB or backend service based on path prefix.
        """
        local_paths, remote_paths = self._split_paths(request.paths)
        
        results = []
        
        # Handle local paths via bridge (using agent's own endpoint)
        if local_paths:
            local_req = GetRequest(paths=local_paths, msg_id=request.msg_id)
            local_response = await self._bridge_request(
                local_req, controller_context, internal=True
            )
            if hasattr(local_response, 'results'):
                results.extend(local_response.results)
        
        # Bridge remote paths to backend
        if remote_paths:
            backend_req = GetRequest(paths=remote_paths, msg_id=request.msg_id)
            backend_response = await self._bridge_request(
                backend_req, controller_context
            )
            # backend_response is a GetResponse object with results attribute
            if hasattr(backend_response, 'results'):
                results.extend(backend_response.results)
        
        return GetResponse(msg_id=request.msg_id, results=results)
    
    async def handle_set(self, request: SetRequest,
                        controller_context: Any) -> SetResponse:
        """Handle USP Set request"""
        # Convert dict parameters to list format expected by _split_set_params
        if isinstance(request.parameters, dict):
            params_list = [{"path": path, "value": value} 
                          for path, value in request.parameters.items()]
        else:
            params_list = request.parameters
            
        local_params, remote_params = self._split_set_params(params_list)
        
        updated_params = {}
        failed_params = {}
        
        # Handle local parameters via bridge (using agent's own endpoint)
        if local_params:
            local_req = SetRequest(parameters={p["path"]: p["value"] for p in local_params}, 
                                  msg_id=request.msg_id)
            local_response = await self._bridge_request(
                local_req, controller_context, internal=True
            )
            if hasattr(local_response, 'updated_params'):
                updated_params.update(local_response.updated_params)
            if hasattr(local_response, 'failed_params'):
                failed_params.update(local_response.failed_params)
        
        # Bridge remote parameters to backend
        if remote_params:
            backend_req = SetRequest(parameters={p["path"]: p["value"] for p in remote_params}, 
                                    msg_id=request.msg_id)
            backend_response = await self._bridge_request(
                backend_req, controller_context
            )
            if hasattr(backend_response, 'updated_params'):
                updated_params.update(backend_response.updated_params)
            if hasattr(backend_response, 'failed_params'):
                failed_params.update(backend_response.failed_params)
        
        return SetResponse(msg_id=request.msg_id, 
                          updated_params=updated_params,
                          failed_params=failed_params)
    
    async def handle_operate(self, request: OperateRequest,
                            controller_context: Any) -> OperateResponse:
        """Handle USP Operate request - always bridge to backend"""
        # Operations are typically on backend services (Reboot(), Reset(), etc.)
        return await self._bridge_request(request, controller_context)
    
    async def handle_add(self, request: Any,
                        controller_context: Any) -> Any:
        """
        Handle USP Add request
        
        Note: AddRequest/AddResponse not yet implemented in message module.
        This is a placeholder for future implementation.
        """
        # Check if adding to LocalAgent (e.g., subscriptions)
        if hasattr(request, 'obj_path') and self._is_local_path(request.obj_path):
            # Use agent's own endpoint for internal requests
            return await self._bridge_request(request, controller_context, internal=True)
        else:
            # Bridge to backend
            return await self._bridge_request(request, controller_context)
    
    async def handle_delete(self, request: Any,
                           controller_context: Any) -> Any:
        """
        Handle USP Delete request
        
        Note: DeleteRequest/DeleteResponse not yet implemented in message module.
        This is a placeholder for future implementation.
        """
        obj_paths = getattr(request, 'obj_paths', [])
        local_paths, remote_paths = self._split_paths(obj_paths)
        
        results = []
        
        # Handle local deletions via bridge (internal)
        if local_paths:
            local_del_req = type('DeleteRequest', (), {
                'obj_paths': local_paths,
                'msg_id': request.msg_id
            })()
            local_results = await self._bridge_request(local_del_req, controller_context, internal=True)
            if hasattr(local_results, 'results'):
                results.extend(local_results.results)
        
        # Bridge remote deletions
        if remote_paths:
            backend_results = await self._bridge_request(request, controller_context)
            if hasattr(backend_results, 'results'):
                results.extend(backend_results.results)
        
        return type('DeleteResponse', (), {
            'msg_id': request.msg_id,
            'results': results
        })()
    
    async def handle_get_supported_dm(self, request: GetSupportedDMRequest,
                                     controller_context: Any) -> GetSupportedDMResponse:
        """Handle GetSupportedDM - combine local and backend data models"""
        local_paths, remote_paths = self._split_paths(request.obj_paths)
        
        results = []
        
        # Get local data model metadata via bridge (internal)
        if local_paths:
            local_req = GetSupportedDMRequest(
                obj_paths=local_paths, msg_id=request.msg_id
            )
            local_results = await self._bridge_request(local_req, controller_context, internal=True)
            results.extend(local_results)
        
        # Get backend data model metadata
        if remote_paths:
            backend_req = GetSupportedDMRequest(
                obj_paths=remote_paths, msg_id=request.msg_id
            )
            backend_results = await self._bridge_request(backend_req, controller_context)
            results.extend(backend_results)
        
        return GetSupportedDMResponse(msg_id=request.msg_id, results=results)
    
    async def handle_get_instances(self, request: GetInstancesRequest,
                                   controller_context: Any) -> GetInstancesResponse:
        """Handle GetInstances request"""
        local_paths, remote_paths = self._split_paths(request.obj_paths)
        
        results = []
        
        # Get local instances via bridge (internal)
        if local_paths:
            local_req = GetInstancesRequest(
                obj_paths=local_paths, msg_id=request.msg_id
            )
            local_results = await self._bridge_request(local_req, controller_context, internal=True)
            results.extend(local_results)
        
        # Get backend instances
        if remote_paths:
            backend_req = GetInstancesRequest(
                obj_paths=remote_paths, msg_id=request.msg_id
            )
            backend_results = await self._bridge_request(backend_req, controller_context)
            results.extend(backend_results)
        
        return GetInstancesResponse(msg_id=request.msg_id, results=results)
    
    # =========================================================================
    # Backend Bridge Communication (TX/RX Channels)
    # =========================================================================
    
    async def _bridge_request(self, request: Any, controller_context: Any,
                            internal: bool = False) -> Any:
        """
        TX Channel: Send request to backend and wait for response
        
        Uses two-channel pattern:
        1. TX: Serialize and send via bridge.send()
        2. RX: Wait for response via future (fulfilled by _backend_response_loop)
        
        Args:
            request: USP request to send
            controller_context: Controller metadata
            internal: If True, uses agent's own endpoint (for local DB queries)
                     If False, uses controller's endpoint (for external requests)
        """
        # Use agent's own endpoint for internal requests (local DB)
        # Use controller's endpoint for external requests
        target_endpoint = self.endpoint_id if internal else getattr(controller_context, 'endpoint', 'unknown')
        
        # Create bridge context
        bridge_context = BridgeContext(
            usp_msg_id=request.msg_id,
            controller_endpoint=target_endpoint,
            mtp_id=getattr(controller_context, 'mtp_id', 'unknown'),
            mac_address=self._get_mac_address(),
            controller_id=getattr(controller_context, 'controller_id', 'unknown')
        )
        
        # Create future for async response
        future = asyncio.Future()
        
        # Track pending request
        self._pending[request.msg_id] = PendingRequest(
            request=request,
            context=bridge_context,
            future=future
        )
        
        try:
            # TX Channel: Send to backend
            self.bridge.send(request, bridge_context)
            logger.debug(f"Sent {'internal' if internal else 'external'} request: {request.msg_id} to {target_endpoint}")
            
            # Wait for response (with timeout)
            response = await asyncio.wait_for(future, timeout=30.0)
            return response
            
        except asyncio.TimeoutError:
            logger.error(f"Backend request timeout: {request.msg_id}")
            raise
        except Exception as e:
            logger.error(f"Backend request failed: {e}")
            raise
        finally:
            # Clean up pending request
            self._pending.pop(request.msg_id, None)
    
    async def _backend_response_loop(self):
        """
        RX Channel: Listen for responses from backend
        
        Continuously reads from backend transport, deserializes responses,
        and fulfills pending request futures.
        """
        while True:
            try:
                # Receive response bytes from backend transport
                # NOTE: This is pseudo-code - actual implementation depends on transport
                response_bytes = await self._receive_from_backend()
                
                if not response_bytes:
                    await asyncio.sleep(0.01)
                    continue
                
                # RX Channel: Deserialize response
                operation, data, context = self.bridge.from_bytes(response_bytes)
                
                # Find pending request by msg_id
                msg_id = context.usp_msg_id
                pending = self._pending.get(msg_id)
                
                if not pending:
                    logger.warning(f"Received response for unknown request: {msg_id}")
                    continue
                
                # Build USP response based on operation type
                response = self._build_response(operation, data, pending.request)
                
                # Fulfill future (unblocks _bridge_request)
                if pending.future and not pending.future.done():
                    pending.future.set_result(response)
                
                logger.debug(f"Received backend response: {msg_id}")
                
            except Exception as e:
                logger.error(f"Backend response loop error: {e}")
                await asyncio.sleep(1)
    
    async def _receive_from_backend(self) -> Optional[bytes]:
        """
        Receive bytes from backend transport
        
        NOTE: This is transport-specific and should be implemented based on
        the actual transport mechanism (nanomsg, UDS, MQTT, etc.)
        """
        # Placeholder - implement based on your transport
        # Example for socket:
        # return await loop.sock_recv(self.backend_socket, 4096)
        await asyncio.sleep(0.1)
        return None
    
    def _build_response(self, operation: str, data: Dict, 
                       request: Any) -> Any:
        """
        Build USP response from backend data
        
        Maps operation type and data to appropriate response object.
        This is simple mapping - no business logic needed!
        """
        if operation == "get":
            return GetResponse(
                msg_id=request.msg_id,
                results=data.get("parameters", [])
            )
        elif operation == "set":
            return SetResponse(
                msg_id=request.msg_id,
                updated_params=data.get("updated_params", {}),
                failed_params=data.get("failed_params", {})
            )
        elif operation == "operate":
            return OperateResponse(
                msg_id=request.msg_id,
                result=data.get("result", {})
            )
        elif operation == "add":
            # Placeholder response for Add (not yet in message module)
            return type('AddResponse', (), {
                'msg_id': request.msg_id,
                'created_obj_path': data.get("created_obj_path", ""),
                'status': data.get("status", "success")
            })()
        elif operation == "delete":
            # Placeholder response for Delete (not yet in message module)
            return type('DeleteResponse', (), {
                'msg_id': request.msg_id,
                'results': data.get("results", [])
            })()
        elif operation == "get_supported_dm":
            return GetSupportedDMResponse(
                msg_id=request.msg_id,
                results=data.get("results", [])
            )
        elif operation == "get_instances":
            return GetInstancesResponse(
                msg_id=request.msg_id,
                results=data.get("results", [])
            )
        else:
            raise ValueError(f"Unknown operation type: {operation}")
    
    # =========================================================================
    # Event Generation (Agent Responsibilities)
    # =========================================================================
    
    async def _send_boot_event(self):
        """
        Send Boot! event
        
        Agent owns Boot! event generation but queries necessary boot parameters
        from the bridge to populate the event with device information.
        
        Boot! event parameters include:
        - SoftwareVersion: From Device.LocalAgent.SoftwareVersion (local)
        - FirmwareVersion: From Device.DeviceInfo.SoftwareVersion (bridged)
        - ParameterMap: Mapping of changed parameters (simplified for now)
        """
        # Query boot-related parameters via bridge
        # These are marked as internal=True since they're part of agent's boot info
        boot_params_request = GetRequest(
            msg_id=f"boot-params-{int(self._boot_time)}",
            paths=[
                "Device.LocalAgent.SoftwareVersion",
                "Device.DeviceInfo.SoftwareVersion",
                "Device.DeviceInfo.Manufacturer",
                "Device.DeviceInfo.ProductClass",
                "Device.DeviceInfo.SerialNumber"
            ]
        )
        
        # Create internal context (using agent's own endpoint)
        boot_context = type('BootContext', (), {
            'endpoint': self.endpoint_id,
            'mtp_id': 'internal',
            'controller_id': 'boot-event'
        })()
        
        # Query boot parameters via bridge (internal request)
        logger.info("Boot! event: Querying boot parameters from bridge...")
        try:
            boot_response = await self.handle_get(boot_params_request, boot_context)
            
            # Extract parameter values
            param_values = {}
            for param_result in boot_response.results:
                if "value" in param_result:
                    # Use 'name' field from response (not 'path')
                    param_name = param_result.get("name") or param_result.get("path")
                    param_values[param_name] = param_result["value"]
            
            logger.info(f"Boot! event: Retrieved {len(param_values)} boot parameters: {list(param_values.keys())}")
            
            # Build Boot! event with queried values
            boot_event = {
                "event": "Boot!",
                "obj_path": "Device.LocalAgent.",
                "params": {
                    "BootTime": int(self._boot_time),
                    "Cause": "LocalReboot",
                    "CommandKey": "",
                    "SoftwareVersion": param_values.get("Device.LocalAgent.SoftwareVersion", "unknown"),
                    "FirmwareVersion": param_values.get("Device.DeviceInfo.SoftwareVersion", "unknown"),
                    "Manufacturer": param_values.get("Device.DeviceInfo.Manufacturer", "unknown"),
                    "ProductClass": param_values.get("Device.DeviceInfo.ProductClass", "unknown"),
                    "SerialNumber": param_values.get("Device.DeviceInfo.SerialNumber", "unknown")
                }
            }
            
            logger.info(f"Boot! event generated with parameters: {boot_event['params']}")
            
        except Exception as e:
            logger.error(f"Boot! event: Failed to query boot parameters: {e}")
            # Fallback to minimal Boot! event
            boot_event = {
                "event": "Boot!",
                "obj_path": "Device.LocalAgent.",
                "params": {
                    "BootTime": int(self._boot_time),
                    "Cause": "LocalReboot",
                    "CommandKey": ""
                }
            }
        
        # Send to controller via MTP layer (not shown here)
        # In a real implementation, this would be sent via the MTP layer
    
    async def _periodic_event_loop(self):
        """
        Generate Periodic! events
        
        Agent owns Periodic! event generation based on configured interval.
        """
        while True:
            try:
                await asyncio.sleep(self._periodic_interval)
                
                periodic_event = {
                    "event": "Periodic!",
                    "obj_path": "Device.LocalAgent.",
                    "params": {
                        "UpTime": int(time.time() - self._boot_time)
                    }
                }
                
                logger.info(f"Periodic! event: {periodic_event}")
                # Send to controller via MTP layer (not shown here)
                
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Periodic event error: {e}")
    
    # =========================================================================
    # Path Routing Helpers
    # =========================================================================
    
    def _split_paths(self, paths: List[str]) -> Tuple[List[str], List[str]]:
        """
        Split paths into local (agent-owned) and remote (backend service)
        
        Returns:
            (local_paths, remote_paths)
        """
        local = []
        remote = []
        
        for path in paths:
            if self._is_local_path(path):
                local.append(path)
            else:
                remote.append(path)
        
        return local, remote
    
    def _split_set_params(self, params: List[Dict]) -> Tuple[List[Dict], List[Dict]]:
        """Split Set parameters into local and remote"""
        local = []
        remote = []
        
        for param in params:
            if self._is_local_path(param.get("path", "")):
                local.append(param)
            else:
                remote.append(param)
        
        return local, remote
    
    def _is_local_path(self, path: str) -> bool:
        """Check if path is handled locally by agent"""
        return any(path.startswith(prefix) for prefix in self.LOCAL_PATHS)
    
    def _get_mac_address(self) -> str:
        """Get device MAC address"""
        # Implement based on your system
        return "112233445566"
